### ISSUE TITLE
AttributeError: module 'select' has no attribute 'poll'

### ISSUE THREAD

**Issue by lucianofara** [akhan23wgu/amazon-alexa-lg-tv#1]
When I run: 
python alexa-tv.py

Error:
Traceback (most recent call last):
  File "alexa-tv.py", line 67, in <module>
    p = fauxmo.poller()
  File "fauxmo.py", line 67, in __init__
    self.poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'

**Comment by akhan23wgu** [comment]
What version of python are you running? "Python -v" to find out.

**Comment by jvance325** [comment]
I am having the same issue actually. I have a fresh install of version 2.7.13 on the machine.

**Comment by lucianofara** [comment]
I tried the version 2.7.13 and 3.6.2 on win10

**Comment by akhan23wgu** [comment]
@jvance325 are you running on Windows as well?

Poll isn't available in Windows. You will need to use Linux or OS X. [@efpe](https://github.com/efpe) suggested to use using the latest Fauxmo from Pypi. [https://pypi.python.org/pypi/fauxmo](https://pypi.python.org/pypi/fauxmo)
See: [https://github.com/efpe/amazon-alexa-lg-tv/issues/7](https://github.com/efpe/amazon-alexa-lg-tv/issues/7)

**Comment by d0x** [comment]
On OSX i had the same error because my python version was without poll: See https://github.com/google/pyringe/issues/14#issuecomment-57856541

`brew reinstall python --with-poll`

should fix it.

**Comment by zhdenny** [comment]
Not sure if this helps people but.....You can just fire these Commands manually from command line in Windows. For example, the command below will Turn on the TV. 

python LGTV.py On

**Comment by akhan23wgu** [comment]
No update from op - closing.
