### ISSUE TITLE
Issue when running alexa-tv.py

### ISSUE THREAD

**Issue by stevena9475** [akhan23wgu/amazon-alexa-lg-tv#11]
Hi, Thanks for this. I got to starting the script after all things successful and auth tv was successful

but when running the alexa-tv.py file i get the below error, im sure its something simple but can you help please?

Traceback (most recent call last):
  File "alexa-tv.py", line 15, in <module>
    import fauxmo
  File "/Users/xxxxxxxxxx/Documents/amazon-alexa-lg-tv-master/fauxmo.py", line 31, in <module>
    import requests
ImportError: No module named requests

**Comment by akhan23wgu** [comment]
Pip install requests

**Comment by stevena9475** [comment]
Hi, if you referring to the requests file in the first steps this was done

Any other suggestions?

**Comment by akhan23wgu** [comment]
It's looking for the module 'requests'. It can't find the module. Normally
if it can't find it, you're missing it. You're using Python 2, right?

**Comment by stevena9475** [comment]
I’m using python 2.7.9

**Comment by akhan23wgu** [comment]
What output did you get when you try installing the requests module?

**Comment by stevena9475** [comment]
sorted the requests i run requirements earlier not requests.

I now have a new issue when running the python alexa-tv.py step

Traceback (most recent call last):
  File "alexa-tv.py", line 69, in <module>
    u.init_socket()
  File "/Users/xxxxxxxxx/Documents/amazon-alexa-lg-tv-master/fauxmo.py", line 300, in init_socket
    dbg("Failed to initialize UPnP sockets:",e)
TypeError: dbg() takes exactly 1 argument (2 given)

**Comment by stevena9475** [comment]
Hi, do you have any suggestions as to what I can try? 

Is it the version of python?

**Comment by stevena9475** [comment]
below extract from requests: 
pip install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Cleaning up...

**Comment by stevena9475** [comment]
When running this: python alexa-tv.py, could not see new devices in alexa app
Output:
DEBUG:root:Failed to initialize UPnP sockets: dbg() takes exactly 1 argument (2 given)
DEBUG:root:got local address of 192.168.0.52
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'tv' ready on 192.168.0.52:52000
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'volume' ready on 192.168.0.52:52002
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'netflix' ready on 192.168.0.52:52003
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'playback' ready on 192.168.0.52:52004
DEBUG:root:UPnP broadcast listener: new device registered
DEBUG:root:FauxMo device 'plex' ready on 192.168.0.52:52001
DEBUG:root:Entering fauxmo polling loop

**Comment by jadonv** [comment]
i'm in the same boat. Everything went flawlessly running python 2.7.13 but won't show up when discovering devices. Any thoughts?

**Comment by stevena9475** [comment]
i have been trying to figure this out but i am stumped! hoping that some dev guru can figure out what im missing :-(

**Comment by pler** [comment]
@jadonv there is an open issue for this (devices aren't showing up) here: https://github.com/akhan23wgu/amazon-alexa-lg-tv/issues/10

**Comment by akhan23wgu** [comment]
Closing - see #10 for similar issue.
