### ISSUE TITLE
Alexa is not discovering the devices

### ISSUE THREAD

**Issue by randv123** [akhan23wgu/amazon-alexa-lg-tv#13]
I have everything running after updating the code to Python 3. Pairing done with the TV. 
But Alexa app does not discover anything.

Don't understand "Mobile TV On" comment in the instructions? what is that?

I am using Echo Dot.
thanks

**Comment by akhan23wgu** [comment]
Under the TV settings, turn on "Mobile Tv"

**Comment by timothe** [comment]
How do you update the code to Python 3? Is there another fork, commit?
I managed to make the original code to run on Python 2 but I encounter the same issue: the Alexa app doesn't find the _Device_.
(_Mobile TV_ is on, and I get the _"Hello World"_ page)

**Comment by DoudouJack** [comment]
Same issue here. When entering discovery mode I see DEBUG:root:Responding to search for tv and all other apps but Alexa app ends saying no new devices found. I launch the script with python 2.7, Mobile TV is on, auth has been done. Edit: python lgtv.py auth X.X.X.X returns {"closing": {"reason": "", "code": 1000}} is it the normal closing code ? I got promped on the tv and accepted.

**Comment by cbarratt** [comment]
i get the exact same @DoudouJack ! has anyone here figured it out?

**Comment by akhan23wgu** [comment]
Code 1000 is normal. If you want a working python 3 build, check out @jamckee's fork [here](https://github.com/jamckee/amazon-alexa-lg-tv)
