### ISSUE TITLE
What do you mean by not supported by Windows?

### ISSUE THREAD

**Issue by StarfighterJ** [akhan23wgu/amazon-alexa-lg-tv#14]
You need a TV with WebOS 2.0+. Compatible with Linux and MacOS (Python poll is not supported by Windows). What does this mean? I look at Python it come with Windows
Also why are you using Python?
Why didn't you use Amazon Developer and Lambda Service in AWS?
Sorry for all the questions I am new at this I just finished up a ALEXA skill to run Directv genie with a Group of other Persons.

**Comment by akhan23wgu** [comment]
"poll" is not supported in the Windows version of Python. This is explained in the readme.

I didn't use Amazon Developer and Lambda because I wanted to run the commands on my local network (I also use HA).
