### ISSUE TITLE
AttributeError: 'module' object has no attribute 'poll'

### ISSUE THREAD

**Issue by shyamkumart** [akhan23wgu/amazon-alexa-lg-tv#15]
i get this error while starting alexa-tv.py.

Traceback (most recent call last):
  File "alexa-tv.py", line 67, in <module>
    p = fauxmo.poller()
  File "/git/amazon-alexa-lg-tv/fauxmo.py", line 67, in __init__
    self.poller = select.poll()
AttributeError: 'module' object has no attribute 'poll'
----
poll==1.0
Python 2.7.10

**Comment by shyamkumart** [comment]
Fixed the issue .

**Comment by stevenp** [comment]
How did you fix the issue?
