### ISSUE TITLE
Error on runining command python lgtv.py auth 192.168.5.4 

### ISSUE THREAD

**Issue by ivangalic18** [akhan23wgu/amazon-alexa-lg-tv#17]
when I run  python lgtv.py auth 192.168.5.4     
I get error
                                            Traceback (most recent call last):
  File "lgtv.py", line 480, in <module>
    ws.connect()
  File "/usr/local/lib/python2.7/dist-packages/ws4py/client/__init__.py", line 217, in connect
    self.sock.connect(self.bind_addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

here are all open ports and model of TV

![capture](https://user-images.githubusercontent.com/41490847/43026465-c572a20a-8c6d-11e8-9232-1b84acc1f9dc.JPG)

**Comment by akhan23wgu** [comment]
Is MobileTV enabled on the TV?

**Comment by ivangalic18** [comment]
![capture](https://user-images.githubusercontent.com/41490847/43032682-fc402644-8cb4-11e8-803a-44103a525b43.JPG)
yes

**Comment by ivangalic18** [comment]
LG TV remote over phone is working normaly but this cool scrip of yours, stuck on this error, please help....

**Comment by akhan23wgu** [comment]
Are you using an Echo, Echo Dot, or a newer Echo device?

This script only works on the Gen1 and Gen2 Echo Dots.

**Comment by ivangalic18** [comment]
I'm using Echo (2nd Generation) = https://www.amazon.com/all-new-amazon-echo-speaker-with-wifi-alexa-dark-charcoal/dp/B06XCM9LJ4

Can we adapt this for newer Echo?

**Comment by ivangalic18** [comment]
Any updates?

**Comment by akhan23wgu** [comment]
Only the Echo Dot is supported. They use a different polling method. Check
out how some other users were able to get it working by using a REST API.
There are a few other forks too that might be worth looking at.
