### ISSUE TITLE
AutoRestart Script Upon Network Error

### ISSUE THREAD

**Issue by zhdenny** [akhan23wgu/amazon-alexa-lg-tv#3]
Simple/Small/Temporary Network Disconnects seem to trigger the script to stop. Is there any way to have the script Restart or NOT stop upon receiving such issues. Error message quoted below.

CRITICAL:root:Critical exception: [Errno 101] Network is unreachable

**Comment by akhan23wgu** [comment]
I found a more actively worked on version of fauxmo (found here: https://github.com/n8henrie/fauxmo).

I don't have time to test it out at the moment, maybe you can give it a shot? It uses Python 3.

**Comment by akhan23wgu** [comment]
No update from OP - closing ticket.
