### ISSUE TITLE
TV ask for accept connection app, in every each command

### ISSUE THREAD

**Issue by Qlinkwisp** [akhan23wgu/amazon-alexa-lg-tv#7]
Hello,

in any command like "turn off the tv" , "turn off the volumn" 
my uh615T lg tv  will ask me to accept connection application. 

Except only "turn on the tv" command

i guess the issue is
- in case of "turn on the tv" is use [wake on lan] to make the TV Start. Unlike the other command that use web socket.

-i try auth command but when accept the connection , ws seem close like this
+++++++
root@beaglebone:/home/amazon-alexa-lg-tv-master# python lgtv.py auth 192.168.1.102
{"closing": {"reason": "", "code": 1000}}
root@beaglebone:/home/amazon-alexa-lg-tv-master#
++++++++

- when use the volumn off command , TV will ask for accept the connection, and then when i accept the command will launch and end with close ws like this

+++++++++++++++++
DEBUG:root:Responding to OFF for volume
State False on  volume from client @ 192.168.1.103
{"type": "response", "id": "0", "payload": {"returnValue": true}}
{"closing": {"reason": "", "code": 1000}}
Volume set to ZERO
+++++++++++++++++

did you found this?

Thank you

**Comment by Qlinkwisp** [comment]
Hello Again

i found good way to solve the issue 

Will update later

 thank you

**Comment by punch69** [comment]
Any update on this? I also get the same error , Thanks!

**Comment by akhan23wgu** [comment]
Try re-authenticating from scratch. Delete the hidden .lgtv.json file in your home directory and then start the auth process again and see if you have the same issue.

**Comment by punch69** [comment]
HI! cleared the .lgtv.json file tried again, "accept" the connection on the TV.  Same issue:

punch69@punch696:~/amazon-alexa-lg-tv$ python lgtv.py auth 192.168.1.197
Please accept the pairing request on your LG TV                             <<<<<< here i accept it
{"closing": {"reason": "", "code": 1000}}

Thank you!

**Comment by akhan23wgu** [comment]
Try clearing the .json file and run the auth as root.

**Comment by punch69** [comment]
Cleared .json in root and my user ( just in case) 

Got the same error,

root@punch696:/home/punch69/amazon-alexa-lg-tv# python lgtv.py auth 192.168.1.197
Please accept the pairing request on your LG TV
{"closing": {"reason": "", "code": 1000}}
root@punch696:/home/punch69/amazon-alexa-lg-tv# 

But now its working!  I can ask Alexa to turn the TV on or off and wont ask me for the paring request.

Thanks!

**Comment by akhan23wgu** [comment]
Awesome you got it sorted out :)
