### ISSUE TITLE
Error running command

### ISSUE THREAD

**Issue by twaltersr** [akhan23wgu/amazon-alexa-lg-tv#9]
Getting the following error when running "python.exe lgtv.py auth 192.168.x.x
File "lgtv.py", line 126
    print e.message
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print e.message)?

I am running PIP and Python from Windows 10.

**Comment by twaltersr** [comment]
I updated the line 126 to read: print (e.message) instead of print e.message and now getting this error.

File "lgtv.py", line 221
    print "Error: Handshake failed"

**Comment by twaltersr** [comment]
After going through the entire file and adding ( ) around each print command, i am now getting this error.

Traceback (most recent call last):
  File "lgtv.py", line 480, in <module>
    ws = LGTVClient(sys.argv[2])
  File "lgtv.py", line 211, in __init__
    self.__macAddress = getMacAddress(self.__ip)
  File "lgtv.py", line 157, in getMacAddress
    matches = re.search(r"(([a-f\d]{1,2}\:){5}[a-f\d]{1,2})", s)
  File "C:\Users\Yoga\AppData\Local\Programs\Python\Python36-32\lib\re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by twaltersr** [comment]
I downgraded to Python 2.7.14 and still getting an error when running "python.exe lgtv.py auth 192.168.x.x"

Traceback (most recent call last):
  File "lgtv.py", line 479, in <module>
    ws = LGTVClient(sys.argv[2])
  File "lgtv.py", line 215, in __init__
    super(LGTVClient, self).__init__('ws://' + self.__hostname + ':3000/', exclude_headers=["Origin"])
TypeError: __init__() got an unexpected keyword argument 'exclude_headers'

**Comment by twaltersr** [comment]
After finally getting past the above issues,  Running "lgtv.py auth 192.168.x.x, and accepting the request on the TV: "Connection Request: LG Remove App" and selecting "Yes" , i get the following error.

{"closing": {"reason": "", "code": 1000}}

py -m c:\Python27\python.exe alex-tv.py
C:\Python27\python.exe: Import by filename is not supported.

**Comment by akhan23wgu** [comment]
Doesn't run in Windows. Try an ubuntu VM or docker container.
